name: JS Find and Replace
description: Use a JS file to find and replace text!
author: ahmed33033

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: search
  color: blue

# Define your inputs here.
inputs:
  find-and-replace-file:
    description: |
      The relative path to the find-and-replace JS file. 

      The JS file must have a default export object with the following properties:
        export default {
            find: string | RegExp   // the thing to find
            replace: string         // the thing to replace
            files: string | Array<string>   // the file(s) to find and replace in
        }
      It can also export an array of objects with the aforementioned properties.

      `files` should contain a relative path to file(s) that will be modified.
      Glob patterns are not allowed; they're too powerful with regex.
    required: true
    default: 'find-and-replace.js'

outputs:
  modified-files:
    description: A space separated string of the modified files.
  modified-files-json:
    description: A string of the modified files formatted as a JSON array.

outputs:
  modified-files:
    description: A space separated string of the modified files.
  modified-files-json:
    description: A string of the modified files formatted as a JSON array.

runs:
  using: node24
  main: dist/index.js
