name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  find_and_replace_file:
    description: |
      The find and replace JS file. This JS file must have a default
      export that exports an array with the following shape:
        Array<{
            find: RegExp
            replace: string
            files: Array<string>
          }>
      Expectedly, any expressions that match `find` will be replaced
      by `replace` in all files in `files`.

      `files` cannot contain any glob patterns; it's too powerful for
      regex use.
    required: true
    default: 'find_and_replace.js'

runs:
  using: node24
  main: dist/index.js
