name: E2E
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup_e2e:
    runs-on: ubuntu-latest
    outputs:
      find-and-replace-files: ${{steps.setup-files.outputs.files}}
      test-obj: ${{steps.setup-files.outputs.test-obj}}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - run: node .github/workflow-utilities/fileListOutputter.js
        id: setup-files
  e2e:
    runs-on: ubuntu-latest
    needs: setup_e2e
    strategy:
      matrix:
        file: ${{fromJson(needs.setup_e2e.outputs.find-and-replace-files)}}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        id: find-and-replace
        with:
          file: ${{matrix.file}}
      - run: node .github/workflow-utilities/fileAsserter.js
        env:
          FIND_AND_REPLACE_FILE: ${{matrix.file}}
          TEST_OBJ: ${{needs.setup_e2e.outputs.test-obj}}
